services:
  - type: web
    name: jamshed-portfolio-assistant
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: COHERE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        value: jamshed-portfolio-assistant
      - key: PYTHON_VERSION
        value: 3.12.3